name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Install project dependencies
      run: npm i
    - name: Fastlane Action
      # You may pin to the exact commit or the version.
      # uses: maierj/fastlane-action@e61c14e51992662d76090be48296e79755f97469
      uses: maierj/fastlane-action@v2.2.1
      with:
        # The lane that should be executed.
        lane: increment_version
        # The relative path from the project root directory to the subdirectory where the fastlane folder is located.
        subdirectory: android
        # The directory where Ruby gems should be installed to and cached. If a relative path is specified, it's applied relative to the location of the Gemfile, which is either the project root or the directory from the `subdirectory` parameter.
        bundle-install-path: android
        # If set to true, adds the verbose option to the fastlane command for extended log output.
        verbose: false
        # The action tracks usage in Firebase by default. You can disable tracking by setting this parameter to 'true'.
        skip-tracking: true
    - name: Grant execute permission for gradlew
      run: chmod +x ./android/gradlew
    - name: Build with Gradle
      run: cd android && ./gradlew assembleDebug
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        # Firebase App ID. You can find it in the Firebase console, on the General Settings page.
        appId: 1:290577007748:android:992dc0bc9e8497fa3baed1
        # Path of IPA or APK file to distribution.
        file: ./android/app/build/outputs/apk/debug/app-debug.apk
        # 'Firebase access token. You can create it by `firebase login:ci` on your local machine.
        token: 1//03XaYOixBEQ10CgYIARAAGAMSNwF-L9IrlkaTmU0AYiQrAe2Ss3f2HwlWBrYJzHc013l9CUMFAhu5S-xzAdBRrJ4YP069HpRJYZI
        # Distribution groups
        groups: githubactionstest-android
