name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Install project dependencies
      run: npm i
    - name: Grant execute permission for gradlew
      run: chmod +x ./android/gradlew
    - name: Build with Gradle
      run: cd android && ./gradlew assembleDebug
    - name: Firebase App Distribution Action
      # You may pin to the exact commit or the version.
      # uses: hasretsariyer/firebase-app-distribution-github-action@1efdc61b2aecd54be4072edb5dd527be26571943
      uses: hasretsariyer/firebase-app-distribution-github-action@v1.0
      with:
        # Firebase App ID. You can find it in the Firebase console, on the General Settings page.
        app_id: 1:290577007748:android:992dc0bc9e8497fa3baed1
        # Path of IPA or APK file to distribution.
        app_file: ./android/app/build/outputs/apk/release/app-debug.apk
        # 'Firebase access token. You can create it by `firebase login:ci` on your local machine.
        firebase_token: 1//03XaYOixBEQ10CgYIARAAGAMSNwF-L9IrlkaTmU0AYiQrAe2Ss3f2HwlWBrYJzHc013l9CUMFAhu5S-xzAdBRrJ4YP069HpRJYZI
        # Distribution groups
        tester_groups: githubactionstest-android
