name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Install project dependencies
      run: npm i
    - name: Grant execute permission for gradlew
      run: chmod +x ./android/gradlew
    - name: Build with Gradle
      run: cd android && ./gradlew assembleDebug
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        # Firebase App ID. You can find it in the Firebase console, on the General Settings page.
        appId: 1:290577007748:android:992dc0bc9e8497fa3baed1
        # Path of IPA or APK file to distribution.
        file: ./android/app/build/outputs/apk/debug/app-debug.apk
        # 'Firebase access token. You can create it by `firebase login:ci` on your local machine.
        token: 1//03XaYOixBEQ10CgYIARAAGAMSNwF-L9IrlkaTmU0AYiQrAe2Ss3f2HwlWBrYJzHc013l9CUMFAhu5S-xzAdBRrJ4YP069HpRJYZI
        # Distribution groups
        groups: githubactionstest-android
